version: "3.8"

services:
  app:
    image: ndp4/mybuilder:latest
    container_name: uas_ecommerce
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_KEY=base64:K0J02VAR5QerU4yVb0DOQ2CKuDUisfPsZ7/Ln1jzTFU=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pseona2
      - DB_USERNAME=laravel
      - DB_PASSWORD=p4rv1zk44n

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "6004:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.5
    container_name: laravel_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pseona2
      MYSQL_USER: laravel
      MYSQL_PASSWORD: p4rv1zk44n
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: laravel_adminer
    ports:
      - "4004:8080"

volumes:
  db_data:
